version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - SPOTIFY_USERNAME=${SPOTIFY_USERNAME}
      - SPOTIFY_PASSWORD=${SPOTIFY_PASSWORD}
      - HOST_ORIGIN=${HOST_ORIGIN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s